namespace RebuildSharedData.Enum.EntityStats;


public enum PlayerStat
{
    Level,
    Status,
    Gender,
    Head,
    HairId,
    Job,
    Exp,
    Experience = Exp,
    JobExp,
    JobExperience = JobExp,
    Str,
    Strength = Str,
    Agi,
    Agility = Agi,
    Vit,
    Vitality = Vit,
    Int,
    Intelligence = Int,
    Dex,
    Dexterity = Dex,
    Luk,
    Luck = Luk,
    Hp,
    Mp,
    SkillPoints,
    StatPoints,
    Zeny,
    JobLevel,
    PushCart,
    PlayerStatsMax
}

public enum CharacterStat
{
    Level,
    Hp,
    MaxHp,
    Sp,
    MaxSp,
    Range,
    Attack,
    Attack2,
    MagicAtkMin,
    MagicAtkMax,
    Str,
    Strength = Str,
    Agi,
    Agility = Agi,
    Vit,
    Vitality = Vit,
    Int,
    Intelligence = Int,
    Dex,
    Dexterity = Dex,
    Luk,
    Luck = Luk,
    Def,
    Defense = Def,
    MDef,
    MagicDefense = MDef,
    AspdBonus,
    MoveSpeedBonus,
    AddStr,
    AddAgi,
    AddDex,
    AddInt,
    AddVit,
    AddLuk,
    AddDef,
    AddMDef,
    AddSoftDefPercent,
    AddFlee,
    AddHit,
    AddAttackPercent,
    AddMagicAttackPercent,
    AddAttackPower,
    AddMagicAttackPower,
    AddDefPercent,
    AddMDefPercent,
    Disabled,
    OverrideElement,
    MonsterStatsMax, //any stats after this are stats only players will be able to hold.

    EndowAttackElement,
    WeightCapacity,
    WeaponMastery,
    EquipmentRefineDef,
    DoubleAttackChance,
    AddSpRecoveryPercent,
    AddHpRecoveryPercent,
    AddMaxHp,
    AddMaxSp,
    AddMaxHpPercent,
    AddMaxSpPercent,
    PerfectDodge,
    AddCrit,
    AddCritDamage,
    AddCastTime,

    AddAttackElementNeutral,
    AddAttackElementEarth,
    AddAttackElementWater,
    AddAttackElementFire,
    AddAttackElementWind,
    AddAttackElementPoison,
    AddAttackElementUndead,
    AddAttackElementDark,
    AddAttackElementHoly,
    AddAttackElementGhost,

    AddResistElementNeutral,
    AddResistElementEarth,
    AddResistElementWater,
    AddResistElementFire,
    AddResistElementWind,
    AddResistElementPoison,
    AddResistElementUndead,
    AddResistElementDark,
    AddResistElementHoly,
    AddResistElementGhost,

    AddAttackRaceFormless,
    AddAttackRaceDemihuman,
    AddAttackRaceBeast,
    AddAttackRaceInsect,
    AddAttackRaceAngel,
    AddAttackRaceDragon,
    AddAttackRaceAquatic,
    AddAttackRacePlant,
    AddAttackRaceDemon,
    AddAttackRaceUndead,

    AddCritChanceRaceFormless,
    AddCritChanceRaceDemihuman,
    AddCritChanceRaceBeast,
    AddCritChanceRaceInsect,
    AddCritChanceRaceAngel,
    AddCritChanceRaceDragon,
    AddCritChanceRaceAquatic,
    AddCritChanceRacePlant,
    AddCritChanceRaceDemon,
    AddCritChanceRaceUndead,

    AddCritDamageRaceFormless,
    AddCritDamageRaceDemihuman,
    AddCritDamageRaceBeast,
    AddCritDamageRaceInsect,
    AddCritDamageRaceAngel,
    AddCritDamageRaceDragon,
    AddCritDamageRaceAquatic,
    AddCritDamageRacePlant,
    AddCritDamageRaceDemon,
    AddCritDamageRaceUndead,

    AddResistRaceFormless,
    AddResistRaceDemihuman,
    AddResistRaceBeast,
    AddResistRaceInsect,
    AddResistRaceAngel,
    AddResistRaceDragon,
    AddResistRaceAquatic,
    AddResistRacePlant,
    AddResistRaceDemon,
    AddResistRaceUndead,

    AddExpRaceFormless,
    AddExpRaceDemihuman,
    AddExpRaceBeast,
    AddExpRaceInsect,
    AddExpRaceAngel,
    AddExpRaceDragon,
    AddExpRaceAquatic,
    AddExpRacePlant,
    AddExpRaceDemon,
    AddExpRaceUndead,
    
    AddAttackSpecialNormal,
    AddAttackSpecialBoss,
    AddAttackRangedAttack,
    AddAttackSmallSize,
    AddAttackMidSize,
    AddAttackLargeSize,

    AddResistSpecialNormal,
    AddResistSpecialBoss,
    AddResistRangedAttack,
    AddResistSmallSize,
    AddResistMidSize,
    AddResistLargeSize,

    IgnoreDefRaceFormless,
    IgnoreDefRaceDemihuman,
    IgnoreDefRaceBeast,
    IgnoreDefRaceInsect,
    IgnoreDefRaceAngel,
    IgnoreDefRaceDragon,
    IgnoreDefRaceAquatic,
    IgnoreDefRacePlant,
    IgnoreDefRaceDemon,
    IgnoreDefRaceUndead,

    IgnoreMDefRaceFormless,
    IgnoreMDefRaceDemihuman,
    IgnoreMDefRaceBeast,
    IgnoreMDefRaceInsect,
    IgnoreMDefRaceAngel,
    IgnoreMDefRaceDragon,
    IgnoreMDefRaceAquatic,
    IgnoreMDefRacePlant,
    IgnoreMDefRaceDemon,
    IgnoreMDefRaceUndead,

    //status effects on attack and defense
    //the order of these (in their set) is important, they need to match that of StatusTriggerFlags

    OnMeleeAttackBlind,
    OnMeleeAttackSilence,
    OnMeleeAttackCurse,
    OnMeleeAttackPoison,
    OnMeleeAttackConfusion,
    OnMeleeAttackHeavyPoison,
    OnMeleeAttackBleeding,
    OnMeleeAttackStun,
    OnMeleeAttackStone,
    OnMeleeAttackFreeze,
    OnMeleeAttackSleep,

    OnMeleeAttackFirst = OnMeleeAttackBlind,
    OnMeleeAttackLast = OnMeleeAttackSleep,

    OnRangedAttackBlind,
    OnRangedAttackSilence,
    OnRangedAttackCurse,
    OnRangedAttackPoison,
    OnRangedAttackConfusion,
    OnRangedAttackHeavyPoison,
    OnRangedAttackBleeding,
    OnRangedAttackStun,
    OnRangedAttackStone,
    OnRangedAttackFreeze,
    OnRangedAttackSleep,

    OnRangedAttackFirst = OnRangedAttackBlind,
    OnRangedAttackLast = OnRangedAttackSleep,

    OnAttackBlindSelf,
    OnAttackSilenceSelf,
    OnAttackCurseSelf,
    OnAttackPoisonSelf,
    OnAttackConfusionSelf,
    OnAttackHeavyPoisonSelf,
    OnAttackBleedingSelf,
    OnAttackStunSelf,
    OnAttackStoneSelf,
    OnAttackFreezeSelf,
    OnAttackSleepSelf,

    OnMeleeStatusSelfFirst = OnAttackBlindSelf,
    OnMeleeStatusSelfLast = OnAttackSleepSelf,

    WhenAttackedBlind,
    WhenAttackedSilence,
    WhenAttackedCurse,
    WhenAttackedPoison,
    WhenAttackedConfusion,
    WhenAttackedHeavyPoison,
    WhenAttackedBleeding,
    WhenAttackedStun,
    WhenAttackedStone,
    WhenAttackedFreeze,
    WhenAttackedSleep,

    WhenAttackedFirst = WhenAttackedBlind,
    WhenAttackedLast = WhenAttackedSleep,

    //WhenAttackedSilence,

    ResistBlindStatus,
    ResistSilenceStatus,
    ResistCurseStatus,
    ResistPoisonStatus,
    ResistConfusionStatus,
    ResistHeavyPoisonStatus,
    ResistBleedingStatus,
    ResistStunStatus,
    ResistStoneStatus,
    ResistFreezeStatus,
    ResistSleepStatus,
    
    DecreasePoisonStatusDamage,
    DecreaseStunDuration,
    DecreaseFreezeDuration,

    PureHpDrain, //effects with 100% chance to recover x% of damage as HP
    PureSpDrain,
    HpDrainChance, //effects that add x% chance to recover y% of damage as HP (doesn't stack with pure hp drain for balance)
    HpDrainAmount,
    SpDrainChance,
    SpDrainAmount,

    HpGainOnAttack,
    SpGainOnAttack,

    HpGainOnKill,
    SpGainOnKill,
    
    HpGainOnAttackRaceFormless,
    HpGainOnAttackRaceDemihuman,
    HpGainOnAttackRaceBeast,
    HpGainOnAttackRaceInsect,
    HpGainOnAttackRaceAngel,
    HpGainOnAttackRaceDragon,
    HpGainOnAttackRaceAquatic,
    HpGainOnAttackRacePlant,
    HpGainOnAttackRaceDemon,
    HpGainOnAttackRaceUndead,

    HpGainOnKillRaceFormless,
    HpGainOnKillRaceDemihuman,
    HpGainOnKillRaceBeast,
    HpGainOnKillRaceInsect,
    HpGainOnKillRaceAngel,
    HpGainOnKillRaceDragon,
    HpGainOnKillRaceAquatic,
    HpGainOnKillRacePlant,
    HpGainOnKillRaceDemon,
    HpGainOnKillRaceUndead,

    SpGainOnAttackRaceFormless,
    SpGainOnAttackRaceDemihuman,
    SpGainOnAttackRaceBeast,
    SpGainOnAttackRaceInsect,
    SpGainOnAttackRaceAngel,
    SpGainOnAttackRaceDragon,
    SpGainOnAttackRaceAquatic,
    SpGainOnAttackRacePlant,
    SpGainOnAttackRaceDemon,
    SpGainOnAttackRaceUndead,

    SpGainOnKillRaceFormless,
    SpGainOnKillRaceDemihuman,
    SpGainOnKillRaceBeast,
    SpGainOnKillRaceInsect,
    SpGainOnKillRaceAngel,
    SpGainOnKillRaceDragon,
    SpGainOnKillRaceAquatic,
    SpGainOnKillRacePlant,
    SpGainOnKillRaceDemon,
    SpGainOnKillRaceUndead,

    KnockOutOnAttack,

    KnockOutOnAttackRaceFormless,
    KnockOutOnAttackRaceDemihuman,
    KnockOutOnAttackRaceBeast,
    KnockOutOnAttackRaceInsect,
    KnockOutOnAttackRaceAngel,
    KnockOutOnAttackRaceDragon,
    KnockOutOnAttackRaceAquatic,
    KnockOutOnAttackRacePlant,
    KnockOutOnAttackRaceDemon,
    KnockOutOnAttackRaceUndead,

    SpConsumption,
    UninterruptibleCast,

    KnockbackImmune,
    ReverseDefense,
    FullRevive, //Osiris card
    NoGemstone,
    MagicImmunity,

    SkillValue, //used to store skill unlocks in ItemEquipState
    AutoSpellOnAttacking,
    AutoSpellWhenAttacked,
    DamageVsTag,
    ResistVsTag,
    NoEffect,
    CharacterStatsMax,
}

public enum TimingStat
{
    MoveSpeed,
    AttackMotionTime,
    AttackDelayTime,
    HitDelayTime,
    SpriteAttackTiming,
    TimingStatsMax
}

public static class PlayerClientStatusDef
{
    public static PlayerStat[] PlayerUpdateData = new[]
    {
        PlayerStat.Level,
        PlayerStat.JobLevel,
        PlayerStat.Zeny,
        PlayerStat.Str,
        PlayerStat.Agi,
        PlayerStat.Int,
        PlayerStat.Vit,
        PlayerStat.Dex,
        PlayerStat.Luk,
        PlayerStat.SkillPoints,
        PlayerStat.StatPoints,
        PlayerStat.JobExperience
    };

    public static CharacterStat[] PlayerUpdateStats = new[]
    {
        CharacterStat.Hp,
        CharacterStat.MaxHp,
        CharacterStat.Sp,
        CharacterStat.MaxSp,
        CharacterStat.AddStr,
        CharacterStat.AddAgi,
        CharacterStat.AddInt,
        CharacterStat.AddVit,
        CharacterStat.AddDex,
        CharacterStat.AddLuk,
        CharacterStat.Def,
        CharacterStat.MDef,
        CharacterStat.Attack,
        CharacterStat.Attack2,
        CharacterStat.MagicAtkMin,
        CharacterStat.MagicAtkMax,
        CharacterStat.AddFlee,
        CharacterStat.AddHit,
        CharacterStat.AddCrit,
        CharacterStat.PerfectDodge,
        CharacterStat.WeightCapacity,
        //CharacterStat.AddSoftDefPercent //add this later, but it'll force a packet revision update
    };
}