using System;
using System.Collections.Generic;
using System.Text;

namespace RebuildSharedData.Enum.EntityStats;


public enum PlayerStat
{
    Level,
    Status,
    Gender,
    Head,
    HairId,
    Job,
    Exp,
    Experience = Exp,
    JobExp,
    JobExperience = JobExp,
    Str,
    Strength = Str,
    Agi,
    Agility = Agi,
    Vit,
    Vitality = Vit,
    Int,
    Intelligence = Int,
    Dex,
    Dexterity = Dex,
    Luk,
    Luck = Luk,
    Hp,
    Mp,
    SkillPoints,
    StatPoints,
    Zeny,
    JobLevel,
    PlayerStatsMax
}

public enum CharacterStat
{
    Level,
    Hp,
    MaxHp,
    Sp,
    MaxSp,
    Range,
    Attack,
    Attack2,
    MagicAtkMin,
    MagicAtkMax,
    Str,
    Strength = Str,
    Agi,
    Agility = Agi,
    Vit,
    Vitality = Vit,
    Int,
    Intelligence = Int,
    Dex,
    Dexterity = Dex,
    Luk,
    Luck = Luk,
    Def,
    Defense = Def,
    MDef,
    MagicDefense = MDef,
    AspdBonus,
    MoveSpeedBonus,
    AddStr,
    AddAgi,
    AddDex,
    AddInt,
    AddVit,
    AddLuk,
    AddDef,
    AddMDef,
    AddSoftDefPercent,
    AddFlee,
    AddHit,
    AddAttackPercent,
    AddMagicAttackPercent,
    AddAttackPower,
    AddMagicAttackPower,
    AddDefPercent,
    AddMDefPercent,
    Disabled,
    OverrideElement,
    MonsterStatsMax, //any stats after this are stats only players will be able to hold.

    EndowAttackElement,
    WeightCapacity,
    WeaponMastery,
    EquipmentRefineDef,
    DoubleAttackChance,
    AddSpRecoveryPercent,
    AddHpRecoveryPercent,
    AddMaxHp,
    AddMaxSp,
    AddMaxHpPercent,
    AddMaxSpPercent,
    PerfectDodge,
    AddCrit,
    AddCritDamage,
    AddCastTime,

    AddAttackElementNeutral,
    AddAttackElementEarth,
    AddAttackElementWater,
    AddAttackElementFire,
    AddAttackElementWind,
    AddAttackElementPoison,
    AddAttackElementUndead,
    AddAttackElementDark,
    AddAttackElementHoly,
    AddAttackElementGhost,

    AddResistElementNeutral,
    AddResistElementEarth,
    AddResistElementWater,
    AddResistElementFire,
    AddResistElementWind,
    AddResistElementPoison,
    AddResistElementUndead,
    AddResistElementDark,
    AddResistElementHoly,
    AddResistElementGhost,

    AddAttackRaceFormless,
    AddAttackRaceDemihuman,
    AddAttackRaceBeast,
    AddAttackRaceInsect,
    AddAttackRaceAngel,
    AddAttackRaceDragon,
    AddAttackRaceAquatic,
    AddAttackRacePlant,
    AddAttackRaceDemon,
    AddAttackRaceUndead,

    AddResistRaceFormless,
    AddResistRaceDemihuman,
    AddResistRaceBeast,
    AddResistRaceInsect,
    AddResistRaceAngel,
    AddResistRaceDragon,
    AddResistRaceAquatic,
    AddResistRacePlant,
    AddResistRaceDemon,
    AddResistRaceUndead,

    AddAttackSpecialNormal,
    AddAttackSpecialBoss,
    AddAttackRangedAttack,
    AddAttackSmallSize,
    AddAttackMidSize,
    AddAttackLargeSize,

    AddResistSpecialNormal,
    AddResistSpecialBoss,
    AddResistRangedAttack,
    AddResistSmallSize,
    AddResistMidSize,
    AddResistLargeSize,

    IgnoreDefRaceFormless,
    IgnoreDefRaceDemihuman,
    IgnoreDefRaceBeast,
    IgnoreDefRaceInsect,
    IgnoreDefRaceAngel,
    IgnoreDefRaceDragon,
    IgnoreDefRaceAquatic,
    IgnoreDefRacePlant,
    IgnoreDefRaceDemon,
    IgnoreDefRaceUndead,

    IgnoreMDefRaceFormless,
    IgnoreMDefRaceDemihuman,
    IgnoreMDefRaceBeast,
    IgnoreMDefRaceInsect,
    IgnoreMDefRaceAngel,
    IgnoreMDefRaceDragon,
    IgnoreMDefRaceAquatic,
    IgnoreMDefRacePlant,
    IgnoreMDefRaceDemon,
    IgnoreMDefRaceUndead,

    OnAttackStun,
    OnAttackPoison,
    OnAttackBlind,
    OnAttackSleep,
    OnAttackFreeze,
    OnAttackCurse,
    OnAttackStone,
    OnAttackSilence,

    WhenAttackedStun,
    WhenAttackedPoison,
    WhenAttackedBlind,
    WhenAttackedSleep,
    WhenAttackedFreeze,
    WhenAttackedCurse,
    WhenAttackedStone,
    WhenAttackedSilence,

    ResistStunStatus,
    ResistPoisonStatus,
    ResistBlindStatus,
    ResistSleepStatus,
    ResistFreezeStatus,
    ResistCurseStatus,
    ResistStoneStatus,
    ResistSilenceStatus,
    ResistConfusionStatus,
    ResistHeavyPoisonStatus,
    ResistBleedingStatus,

    DecreasePoisonStatusDamage,
    DecreaseStunDuration,
    DecreaseFreezeDuration,

    HpDrainChance,
    HpDrainAmount,
    SpDrainChance,
    SpDrainAmount,

    HpOnAttack,
    SpOnAttack,

    SpConsumption,
    UninterruptibleCast,

    SkillValue, //used to store skill unlocks in ItemEquipState
    AutoSpellOnAttacking,
    AutoSpellWhenAttacked,
    NoEffect,
    CharacterStatsMax,
}

public enum TimingStat
{
    MoveSpeed,
    AttackMotionTime,
    AttackDelayTime,
    HitDelayTime,
    SpriteAttackTiming,
    TimingStatsMax
}

public static class PlayerClientStatusDef
{
    public static PlayerStat[] PlayerUpdateData = new[]
    {
        PlayerStat.Level,
        PlayerStat.JobLevel,
        PlayerStat.Zeny,
        PlayerStat.Str,
        PlayerStat.Agi,
        PlayerStat.Int,
        PlayerStat.Vit,
        PlayerStat.Dex,
        PlayerStat.Luk,
        PlayerStat.SkillPoints,
        PlayerStat.StatPoints,
        PlayerStat.JobExperience
    };

    public static CharacterStat[] PlayerUpdateStats = new[]
    {
        CharacterStat.Hp,
        CharacterStat.MaxHp,
        CharacterStat.Sp,
        CharacterStat.MaxSp,
        CharacterStat.AddStr,
        CharacterStat.AddAgi,
        CharacterStat.AddInt,
        CharacterStat.AddVit,
        CharacterStat.AddDex,
        CharacterStat.AddLuk,
        CharacterStat.Def,
        CharacterStat.MDef,
        CharacterStat.Attack,
        CharacterStat.Attack2,
        CharacterStat.MagicAtkMin,
        CharacterStat.MagicAtkMax,
        CharacterStat.AddFlee,
        CharacterStat.AddHit,
        CharacterStat.AddCrit,
        CharacterStat.PerfectDodge,
        CharacterStat.WeightCapacity,
    };
}